name: ASCBCore
version: ${version}
description: A-SCB Core
authors: [Nivk_, SimonMC, Bailey_, WesJD]
main: ascb.nivk.core.Main
depend: [ProtocolLib, NametagEdit, Vault]
commands:
  ascb:
    description: View info about the project
  giverank:
    description: Give rank to a player
  info:
    description: View your info
  contributors:
    description: People who helped
  ban:
    description: Ban people
    aliases: [aban, ascbban, scbban, pban]
  kick:
    description: Kick people
    aliases: [akick, ascbkick, scbkick, pkick]
  class:
    description: Choose a class